spring:
  application:
    name=employee-management
  datasource:
    url: jdbc:postgresql://localhost:5432/Practice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    sql:
      init:
        platform: postgres